CORE_TOOL_SEQUENCE = ["comprehensive_analysis", "recommend_transfers"]
ALL_CORE_TOOLS = set(CORE_TOOL_SEQUENCE)
MAX_PREVIOUS_STEPS_PROMPT = 2
MAX_RECENT_TOOL_RESULTS_PROMPT = 1
MAX_RETRIEVAL_DOCS_PROMPT = 1
MEMORY_CONTEXT_MAX_CHARS_DEFAULT = 600
